// Generated by update-versions.js. Do not edit: this file is excluded from its own hashes.
(() => {
  const identity = {"schema":"mxs-004.clock-sync-pcm.build-identity","version":1,"algorithm":"sha256","components":{"senderCritical":"ee2aa2aa6d694f1ce046c91fa4cc536ec3bc5cbfefea285614a029f874ba64fd","tauriCastingBackend":"868eea413bb8843e2674265834e62a392f893abcf965c2334cdd2bfcbc3c68ab","receiverHtml":"a4207f93ca2356233d0d1f5224932fc35aeae4a1aa7ffdc065c4e70fc54cffae","receiverLogic":"23cab6b5ca88d22a1513acdec1f13714caa6c2d1ce6f958f029d86523a2d8b16","receiverPcmWorklet":"64fd581ee2e97beb3ab9bd6fed02af37888d7c2a4cc1ab9192493e4211555c24"}};
  Object.freeze(identity.components);
  Object.freeze(identity);
  Object.defineProperty(window, "MXS_BUILD_IDENTITY", { value: identity, writable: false, configurable: false });
})();
