// Generated by update-versions.js. Do not edit: this file is excluded from its own hashes.
(() => {
  const identity = {"schema":"mxs-004.clock-sync-pcm.build-identity","version":1,"algorithm":"sha256","components":{"senderCritical":"97eb02a42a3836b2a3b6a2a93535e7db1be65aabafe8eff29399c292911dd8cf","tauriCastingBackend":"4c173b1638b5da2e80b72da7df2c4f027dc77ac6fac9e3a6c60e9889be817483","receiverHtml":"9218baeb797041bad584afc7bd06261405d50c131cd618f4a39ef40ee6431f1b","receiverLogic":"a2dc2b2734051c8957940ad2f7c0608d6350d529829060c640d9c2166b7c9654","receiverPcmWorklet":"b360963cf72c9808a8ca26cfef0c9feb0c753ac1fffc189b0b6add88c943a81b"}};
  Object.freeze(identity.components);
  Object.freeze(identity);
  Object.defineProperty(window, "MXS_BUILD_IDENTITY", { value: identity, writable: false, configurable: false });
})();
