// Generated by scripts/build/update-versions.js. Do not edit: this file is excluded from its own hashes.
(() => {
  const identity = {"schema":"mxs-004.cast-compatibility","version":2,"algorithm":"sha256","artifacts":{"senderCritical":"a1837db7b55e368dcf384625c78e98896b3f33bc72a574754da68f475b89f34c","tauriCastingBackend":"38ef68d73f50ab66643f56ce4e00cbbfc45c29f3e999bfa8fb2ae932c120d980","receiverHtml":"9e1893bebcb2c9ad137b1401b04276b91e0b1d1b16240f2dbadb97aa3fb61378","receiverLogic":"bbb316481566317372a3908b36b30b97d41e7fca95b51c7be78c6a67a72d2ff4","receiverPcmWorklet":"710baac5ddd1af00ac75af664e76803bba453c24cc7fafe9b6242a28a127d846"},"protocols":{"audio":"mxs-004.clock-sync-pcm.v2","gui":"mxs-004.cast-gui.v3","session":"mxs-004.cast-session.v1"},"schemas":{"pcm":"mxs-004.pcm-v2","gui":"mxs-004.gui-v3","actions":"mxs-004.gui-actions.v1"},"capabilities":["gui_actions","gui_state","native_caf","pcm_fallback"]};
  for (const section of ["components", "artifacts", "protocols", "schemas", "capabilities"]) {
    const value = identity[section];
    if (value && typeof value === "object") Object.freeze(value);
  }
  Object.freeze(identity);
  Object.defineProperty(window, "MXS_BUILD_IDENTITY", { value: identity, writable: false, configurable: false });
})();
